version: "3.9"

services:
  backend:
    image: merkandez/backend:2.0
    container_name: backend_container
    ports:
      - "8001:8001"

  frontend:
    image: merkandez/frontend:2.0
    container_name: frontend_container
    ports:
      - "3000:80"
