version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "8001:8001"
    env_file:
      - ./backend/.env

  frontend:
    build: ./front
    container_name: frontend_container
    ports:
      - "3000:80"
